device: cuda
out_dir: "output"

augment:
  normalize:
    mean: [ 0.485, 0.456, 0.406 ]
    std: [ 0.229, 0.224, 0.225 ]
  resize:
    size: 256

data:
  data_dir: "input"
  batch_size: 2
  views: 6

prior_path: "data"

model:
  checkpoint: "best.model"
  encoder:
    feat_dim: 128
    output_size: 16
  attention:
    layer: 6
